### ISSUE TITLE
Upgrade to NET5

### ISSUE THREAD

**Issue by arivera12** [arivera12/BlazorDownloadFile#28]
https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio

**Comment by arivera12** [comment]
This upgrade may help fix and improve this issues but this may require to upgrade to NET5, it seems worth for blazor wasm to increase download speed in a exponential way.

**Comment by surgicalcoder** [comment]
This is now a breaking change in .net 6.0 - https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/6.0/byte-array-interop

You get the following error:

```
Error: Microsoft.JSInterop.JSException: sBase64.replace is not a function
TypeError: sBase64.replace is not a function
    at base64DecToArr (eval at <anonymous> (https://localhost:6001/_framework/blazor.server.js:1:3466), <anonymous>:31:27)
    at BlazorDownloadFile (eval at <anonymous> (https://localhost:6001/_framework/blazor.server.js:1:3466), <anonymous>:3:18)
    at https://localhost:6001/_framework/blazor.server.js:1:3466
    at new Promise (<anonymous>)
    at Ct.beginInvokeJSFromDotNet (https://localhost:6001/_framework/blazor.server.js:1:3440)
    at https://localhost:6001/_framework/blazor.server.js:1:70741
    at Array.forEach (<anonymous>)
    at Ct._invokeClientMethod (https://localhost:6001/_framework/blazor.server.js:1:70727)
    at Ct._processIncomingData (https://localhost:6001/_framework/blazor.server.js:1:68769)
    at yt.Ct.connection.onreceive (https://localhost:6001/_framework/blazor.server.js:1:63169)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
```

**Comment by arivera12** [comment]
I will try take a look how to upgrade this with backward compatibility.

**Comment by TanayParikh** [comment]
Hello @arivera12, I'd recommend skipping .NET 5 and going straight to .NET 6 in this case as .NET 6 has significant improvements to the byte array interop mechanisms. 

Blazor no longer Base64 encodes/decodes `byte[]`, and also natively supports streaming via `JSStreamReference`/`DotNetStreamReference`. This'll provide **SIGNIFICANT** improvements to stability and performance over .NET 5 in this area.

Links:
- https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-6/#efficient-byte-array-transfer-in-javascript-interop
- https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-7/#blazor-streaming-interop-from-javascript-to-net
- https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-7/#large-file-upload-faster-file-uploads-with-blazor
- https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-rc-1/#net-to-javascript-streaming

**Comment by arivera12** [comment]
@TanayParikh yes this is a huge performance boost.

I see people having issues at this moment with net5 and net6.

I will try separate a space on the weekend to upgrade this with backward compatibility

**Comment by arivera12** [comment]
Please download latest version 2.3.0.
